# Domyslna ustawienie wlaczenia pluginu.
# Zawsze mozesz go wlaczyc lub wylaczyc komenda /anti-bot status <enable|disable>
enabled: true
# Lokalizacja folderu z graczami
file-directory: './plugins/Anti-Bot/players'
# Ustawienia rodzajow ochrony
options:
  # Rejestracja kont
  accounts: true
# Wiadomosc do gracza przy stworzeniu konta
# Zmienne:
#     $player - nick gracza,
#     $hostname - nazwa hosta,
#     $uuid - UUID gracza,
#     $ip - IP gracza
kick-message:
- '&&aTwoje konto zostalo pomyslnie utworzone.'
- '&&aProsimy, zaloguj sie ponownie na nasz serwer!'
